import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:valo_chat_app/app/data/models/register.dart';
import 'package:valo_chat_app/app/data/models/user.dart';
import 'package:valo_chat_app/app/modules/auth/login/login.dart';
import 'package:valo_chat_app/app/modules/auth/register/register.dart';
import 'package:valo_chat_app/app/modules/home/home.dart';
import 'package:valo_chat_app/app/widgets/widgets.dart';
import 'package:valo_chat_app/app/themes/theme.dart';
import 'package:pinput/pin_put/pin_put.dart';
import 'package:country_picker/country_picker.dart';

part 'auth_binding.dart';
part 'auth_screen.dart';
part 'auth_controller.dart';
part 'otp_screen.dart';
